# Introduction {#intro}

Within the modern framework of industrialized society, economic growth across most sectors relies on energy from fossil fuels [(Caldeira & Brown 2019)](https://www.pnas.org/doi/epdf/10.1073/pnas.1819605116). It is because of this relationship that, in many cases, economic growth and carbon emissions increase in tandem. The Environmental Kuznets Curve (EKC) hypothesizes that environmental degradation, greatly caused by these industrial emissions, is inevitable during economic development, but is reverted through the liberalization of prospering economies [(Dasgupta et al. 2002)](https://pubs.aeaweb.org/doi/pdfplus/10.1257/0895330027157). While others argue that the continuation of emissions-based economies will trigger climate feedbacks (e.g., rising temperatures and flooding) that will slow economic growth and, in turn, reduce emissions [(Woodard et al. 2019)](https://www.pnas.org/doi/abs/10.1073/pnas.1805187115). Yet neither of these theories arrives at the ideal resolution in which both: economic growth consistently advances and emissions cease or occur at a less frequent rate. This unresolved tension begs the question: can Pareto optimality be met between economic growth and carbon emissions?

Economic production is often constrained by energy availability, as sectors such as industry and transportation require substantial amounts of energy to remain competitive. Since the dawn of the Industrial Revolution, fossil fuels have been the primary source of energy due to its efficiency and reliability. In fact, in 2022, fossil fuels made up for 82% of the world’s energy mix [(Igini 2024)](https://earth.org/fossil-fuel-accounted-for-82-of-global-energy-mix-in-2023-amid-record-consumption-report/). Infrastructure for fossil fuel energy usage was put in place before the threat of anthropogenic carbon emissions was fully realized. Although carbon-free alternatives have become increasingly cost effective in recent years, considerable challenges (e.g., infrastructural reconfiguration) hinder executives from decarbonization [(Caldeira & Brown 2019)](https://www.pnas.org/doi/epdf/10.1073/pnas.1819605116). 

Global inequalities are another barrier to decarbonization. As developed countries transition from industrial-based economies to service-based economies, they outsource their manufacturing needs over to countries where there is a lower cost of production (i.e., developing countries) [(Rooper 2024)](https://clcouncil.org/blog/emissions-growth-in-the-developing-world/). Developing countries rely on these emissions-heavy industries for economic growth, and their impact is far from miniscule. In the past decade, 95% of global emissions increases are attributed to developing countries [(Rooper 2024)](https://clcouncil.org/blog/emissions-growth-in-the-developing-world/). Rather than a shift of emissions, there is a surge of them. While developing countries wipe their hands of much of the direct responsibility, they contribute to a greater problem that is vastly counterproductive.

To address these unresolved issues, ‘decoupling’ has been introduced as a framework to assess a healthy balance between economic development and environmental degradation. There are two types of decoupling (i.e., relative and absolute). Relative decoupling refers to when rates of economic growth exceed rates of environmental harm [(Mattauch et al. 2018)](https://ourworldindata.org/shrink-emissions-not-the-economy). Absolute decoupling is when economic growth is sustained while environmental harm decreases [(Mattauch et al. 2018)](https://ourworldindata.org/shrink-emissions-not-the-economy). Between 1990 and 2012, China exhibited relative decoupling, where there GDP skyrocketed and their energy and material usage rose at a less significant pace [(Ward et al. 2016)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0164733&trk=public_post_comment-text#sec004). Countries within the Organization for Economic Co-Operation and Development (OECD), including the USA and Germany, exhibited signs of absolute decoupling [(Ward et al. 2016)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0164733&trk=public_post_comment-text#sec004). While empirical evidence suggests decoupling is occurring in wealthier countries, the possibility of decoupling happening on a global scale remains a debated topic [(Mattauch et al. 2018)](https://ourworldindata.org/shrink-emissions-not-the-economy). 

The United Nations Sustainable Development Goals [(SDGs)](https://sdgs.un.org/goals), particularly SDG 8 (i.e., decent work and economic growth) and SDG 13 (i.e., climate action), are extremely relevant to this topic. One goal is not to be held with greater importance than another. Economic growth should continue without bearing the same environmental impact as it does today. And climate action must be taken without disturbing economies. To meet these expectations, there needs to be a greater emphasis on SDG 9 (i.e., industry, innovation, and infrastructure) and SDG 12 (i.e., responsible consumption and production). Each of these SDGs work in conjunction. Only through aligning industries with responsible yet effective production can sustained economic growth be achieved while mitigating climate damage.
