# Discussion

Decarbonization is a highly polarized topic because people assume that decarbonization of economies automatically means a reduction in economic growth [(Mattauch et al. 2018)](https://ourworldindata.org/shrink-emissions-not-the-economy). While it's a fair assumption because of the globally storied relationship between economic growth and carbon emissions, it disregards the recent empirical evidence that points to the contrary. From 1995 to 2019, Sweden exhibited absolute decoupling, increasing its net GDP a little over 50% while decreasing consumption-based emissions per capita over 12% [(Ritchie 2021)](https://ourworldindata.org/energy-gdp-decoupling). Sure, Sweden has grown a successful, service-based economy. But this decrease adjusts for offshore imports and exports, highlighting the fact that developed countries do not have to pin high emissions on developing countries to sustain economic growth.
	
While analyzing decoupling from a macroeconomic perspective can help gauge the possibility of decoupling, a true understanding of how this objective can be met lies in tackling cross-sectoral or micro-level realities. Until recently, little knowledge on sectoral or firm-level emissions existed [(Li et al. 2024)](https://www.sciencedirect.com/science/article/pii/S0195925523002627#ab0005). But as more research is done, strategists can better understand which sectors can effectively decouple carbon emissions from economic output using modern technology, and which require further research and development (R&D). 
	
Through decoupling indicators and decomposition analysis a recent study conducted in China assesses the primary drivers of national carbon emissions at the firm level and projects the state of decoupling across sectors [(Li et al. 2024)](https://www.sciencedirect.com/science/article/pii/S0195925523002627#ab0005). The researchers found that mining, textile, and production and supply firms would experience unstable decoupling as current infrastructure and operations within these industries are extremely fossil-fuel reliant [(Li et al. 2024)](https://www.sciencedirect.com/science/article/pii/S0195925523002627#ab0005). This means these sectors need to invest in R&D that prioritizes energy efficiency before they can sufficiently decouple. More optimistically, the researchers also projected strong decoupling states for resource processing and mechatronics manufacturing firms [(Li et al. 2024)](https://www.sciencedirect.com/science/article/pii/S0195925523002627#ab0005). These modern firms benefit from being far more technologically advanced, allowing them to be flexible in improving efficiency. This contrast between sectors reinforces that decoupling is not a uniform process. Rather, it is contingent on the sector-specific characteristics that drive output and emissions (e.g., infrastructure, energy usage, etc.). 
	
It is because of the vast differences across industries that decarbonization cannot be a blanket process. A developing country cannot set out to decarbonize their entire economy at once or they will experience a crash. Steps toward decarbonization are gradual. Investment in R&D ought to be the priority for hard-to-abate industries that require further innovation to reach absolute decoupling. While more adaptable industries can scale modern solutions that will make an immediate impact. Therefore, decarbonization should be tailored to specific sectors rather than entire economies. 


